---
title: "Proposal"
author: "Sam Tyner"
date: "September 9, 2016"
output: pdf_document
bibliography: docs/bigbib.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Outline

### High Level Introduction

Social networks have been studied for decades, beginning with the seminal 1967 study, "The Small World Problem" by Stanley Milgram  (Goldenberg et al. 2009). In recent years, the study of social networks has grown in popularity due to an increase in the availability of and easy of access to social network data. 

* discuss the data format and how it is different from traditional data formats seen in statistics
* bring up the different disciplines that have studied social networks
* mention the models that exist for social network analysis
* mention that I am focusing on one type of model class, SAOMs.

### More Meaty Introduction to Network Analysis

In this section I will discuss in greater detail the models that are out there for network analysis. These include:

* Classics:
    + ERGMs
    + Erdos-Renyi and its variations
    + Random graphs with fixed degree distribution
    + Blockmodels and their relatives
    + Laten space models
* Social Networks:
    + "$p_1$" models
    + "$p_2$" models
* Dynamic:
    + Preferential attachment
    + Small-world
    + Duplication-attachment
    + Discrete time MC models
    + Continuous time MC models (SAOMs a kind of CTMC)
  
### Why focus on SAOMs

First, I will layout the field of network analysis formally using traditional statistical paradigms, as discussed in Kolaczyk (2009). Then I will discuss the lack of model checking tools specific to SAOMs due to model intractibility. This will be brief and will lead into the next section, a complete introduction to SAOMs and their structure/properties. 


### Full introduction and discussion of SAOMs

I will completely flesh out the form and theory of SAOMs. This will come primarily from the detailed document I created last year and anything else from Snijders' papers. 

### Lead-in to Visual Inference 

Take the theory of SAOMs and lead into the discussion of why visual inference could be useful for model checking and other things for SAOMs. 

### Introduction to Visual Inference

Fully introduce the concept of visual inference as laid out in Buja et al. (2009). Also include discussion of Majumder et al. 

### Using visual inference for SAOMs

Explain how I will use visual inference to explore properties of SAOMs. 

### Intro to visualizing networks

Discuss the many ways to visualize networks (also called network mapping). Ubiquitous view is 2D represetation of points and lines. Discuss the many layout algorithms. Discuss the many packages in R that can do this. Discuss the difficulty of using these package for people not intimately familiar with them. Lead into next section with discussion of ggplot2 and its importance and popularity in data visualization.

### Why a ggplot2 wrapper? 

Explain the hole filled by the geomnet package. 

### Summary and Impact

Brief walk-through of all topics already covered. Emphasize the holes filled by the work. 

### Other Projects??? 

Discuss the Bob Ross and Graphics Awards papers? 

\newpage

# Introduction

Social networks have been studied for decades, beginning with a few foundational works, the most well known of which is the 1967 study, "The Small World Problem" by Stanley Milgram (@goldenberg09). But in recent years, the study of social networks has grown wildly in popularity due to an increase in the availability of and easy of access to social network data. The digital revolution has led to the creation of social media, linking people from all over the world in a way we never have been before. Now that platforms like Facebook, Twitter, and LinkedIn permeate our world, just about everyone knows what social networks are. In academic circles, collaboration networks are a type of social network that have been extensively studied and can even be a point of pride, like a mathematician's Erd&#x00F6;s  number (@erdos). Social networks are a rich source of knowledge, but the data format does not fit easily within traditional data collection paradigms. Traditionally, data collection involves a set of units of the same, or at least similar, kind, on which observations are made. The storage of traditional data is simple and organized: rows contain variable values collected from units. These units can be people, plants, animals, stocks, objects, fields, and anything else under the sun, but one social network consits of many units, yet on the whole is just one observation. When observing a social network, one observes the possibly very numerous actors (also referred to as vertices or nodes) and the relationships (also referred to as edges or ties) between those actors. One can also collect information on the nodes and the edges separately, such as the age or gender of people and the length of their relationship or how strong it is in a friendship network. Thus, information on the entire network is more difficult to store than traditional data with which statisticians usually work. 

This apparent difficulty has not stopped researchers in many different fields from studying social and other types of networks. Sociologists work with human relationship networks of all kinds imaginable, biologists work with protein-protein interaction networks, neurologists use fMRI scans to study biologic neural networks, and the list goes on. These disciplines worked separately for many years, each developing their own measures, softwares, and theories about the fundamental properties of networks. And although statisticians were comparatively late to the party, many statistical models exist for network analysis. Beginning with the classic Erd&#x00F6;s-&#R00E9;nyi random graph model and varying in structure, complexity, and application to include longitudinal network data, such as continuous time markov chain models (@goldberg09). The many varying models that exist just for social network analysis are impressive, but I focus my research on one type of continuous time markov chain (CTMC) models, called Stochastic Actor-Oriented Models (SAOMs). A full introduction to the various models that exist for social network analysis is presented in the next section, and a full introduction to the structure and theory of SAOMs is presented in section 3. 

# Statistical Models for Social Networks

# Stochastic Actor-Oriented Models for Longitudinal Social Networks. 

 

# References

