# Stochastic Actor-Oriented Models for Longitudinal Network Data: Removing the Blindfold {#ch1}

**Abstract**: In this chapter, I will "remove the blindfold" from some aspects of modeling social networks with stochastic actor-oriented models. I will follow procedures similar to those in @Wickham2015 in order to better understand the latent process of edge creation and destruction that characterizes a SAOM. I will also visualize, compare, and contrast several different networks simulated from a SAOM with a particular set of parameters and parameter values in order to better understand what the distribution of networks under SAOM looks like. Finally, I will compare large numbers of networks using tools like structural principal components analysis in order to determine how differences in model structure and parameter values affect the overall structure of a social network. 

## Introduction

Network analysis has earned much interest in fields suchs as sociology or computer science. Many methods of analysis for networks have been derived from researchers in these fields, and the interest in network analysis in these fields has grown exponentially throughout the last two decades. There are now entire journals dedicated to network analysis, including *Network Science* and *Social Networks*. In the field of statistics, however, not much attention has been given to this area. There are several possible reasons for this, the first being that statistical network analysis does not fit easily into the statistician’s workflow and way of thinking. 

First and foremost, when modelling, statisticians consider the population from which their data were generated. In some social network problems, this is easy, like in the students at a university example. In others, however, it might not be so straightforward, like when mapping the interconnectedness of scientific disciplines (@Kolaczyk2009). Next, statisticians consider the representativeness of their data. Usually, a random sample of the population has been carefully selected for analysis to be representative. But in network analysis, there may not be a well-designed, appropriate sampling procedure. Social media networks have become very popular and very large, so many researchers have interest in studyin them, but how can they be sampled? Additionally, how does one avoid biases in social network sampling, and can these biases be corrected for (@Kolaczyk2009). If one wants to summarize their network data, what statistics should be used? Measure such as like mean and variance are available and presented for most types of statistical, but there is no definition for a "mean" or a "variance" on a network. So, other statistics like average outdegree are often used. But ultimately, these statistics cannot describe the network structure as well as the mean and variance can describe the distribution of a random variable. As was shown in section \@ref(models) there are many models for network analysis, but once a network is modeled, how can we make predictions for what new networks will be or what new edges will form? 

Furthermore, traditional statistical models have some common properties that network models might not always have. First, the models have to be well-grounded in measure and probability theory so that their behavior can be well-understood based on the fundamentals of these areas of study. This may be true in many network models, but they may also be analytically intractable. Second, the models have to be estimable from the data at hand. Again, this is possible in many of the network models, but some may only be estimable with advanced simulation methods that have only recently become available with respect to computing power. Next, a crucial element within statistics is the quantification of uncertainty in estimation. Since there is not a measure of "variance" on a network, how then can the estimation of network model parameters be qualified to include uncertainty? Finally, statisticians require methods to validate goodness-of-fit of their models. In network analysis, however, goodness-of-fit measures are nearly non-existent (@Kolaczyk2009). 

The introduction to this chapter will also serve as a brief introduction to the structure of stochastic actor-oriented models (SAOMs) for longitudinal network data. As there is a greater exposition of these models in the literature review, I do not repeat that information here at this time. 

## Visualizing the Dynamic Network Process

The basis for SAOMs is a continuous-time Markov chain (CTMC) that remains entirely unobserved with the exception of the finite number of network observations, $T \geq 2$.  The first part of this chapter will discuss a to-be-developed procedure to visualize the intermediary steps in the Markov chain that lead to the network transformation from one time point to another. This video (or interactive app ?) will clearly demonstrate the multilevel process the SAOMs are modelling. First, it will show that a node is selected and given the opportunity to change a tie, and then it will show how that node's objective function decides which tie to change, or to not change at all. 

## Characterizing a SAOM

My hope is that this demonstration will also raise some important questions in the minds of researchers working with these social network models and others. Primarily, I hope to bring question of the model *distribution* to the forefront. The process being modeled is random, and as such has a theoretical underlying distribution. What does that distribution look like? This is an open question in statistical network analysis. In statistics, the entity being modeled is assumed to have an underlying distribution according to any level complexity of model. Even in situations of analytical intractability, data can be simulated in some way or another in order to give the researcher an idea of what the distribution of the model looks like. These distributions can be viewed with histograms or barcharts, or with contour plots, heat maps, or 3D plots for higher dimensional data. But none of these statistical graphics are appropriate for most network models, including SAOMs. Thus, I will aim to create a way to, given various parameter values, visualize the distribution of a SAOM. One area which I will explore to accomplish this task is principal component analysis for graph data. 

Once a distribution is characterized and viewable, the next things people notice are what the average value from this distribution looks like and how spread out the distribution is. Therefore, my next task will be to come up with a way to compute and view the "average" network from a given SAOM, as well as some measure of variability so that researchers can more easily determine whether or not an observed network or set of networks could possibly have come from a given model. 